server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defalutZone: http://localhost:8761/eureka
spring:
  application:
    name: discovery-service
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: webclient