server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
#        git:
#          uri: file:\\\${user.home}\Desktop\config-repo
#          default-label: master
        native:
          search-locations: file:\\\${user.home}\Desktop\Rabbitmq-SpringCloudBus\config-repo
management:
  endpoints:
      exposure:
        include: refresh, health, busrefresh, info

